matrix:
  include:
    # XCode 6.4, OS X 10.10
    - os: osx
      osx_image: xcode6.4

    # XCode 7.3, OS X 10.11
    - os: osx
      osx_image: xcode7.3
      
      # Default OS X image for Travis (10.12, XCode 8.something)
    - os: osx
